export const GET_NEXT_PAGE = 'FILTER/GET_NEXT_PAGE';
export const GET_PREV_PAGE = 'FILTER/GET_PREV_PAGE';
export const MOVIE_YEAR = 'FILTER/MOVIE_YEAR';
export const MOVIE_TITLE = 'FILTER/MOVIE_TITLE';
export const REQUEST_TYPE = 'FILTER/REQUEST_TYPE';
export const CURRENT_PAGE = 'FILTER/CURRENT_PAGE';
export const PAGE_COUNT = 'FILTER/PAGE_COUNT';
