export const MOVIE_LIST_REQUEST = 'PAGE/MOVIE_LIST_REQUEST';
export const MOVIE_LIST = 'PAGE/MOVIE_LIST';
export const MOVIE_DETAIL_REQUEST = 'PAGE/MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL = 'PAGE/MOVIE_DETAIL';
export const MOVIE_DETAIL_REQUEST_SUCCESS = 'PAGE/MOVIE_DETAIL_REQUEST_SUCCESS';
export const MOVIE_DETAIL_REQUEST_FAIL = 'PAGE/MOVIE_DETAIL_REQUEST_FAIL';
